action:
  title: This action with custom widget
  description: Custom widget
  image: buildargs:latest
  build:
    context: ./
    tags:
      - buildargs:latest
    args:
      textArea:
        title: Custom Text area
        description: Using UI schema options and custom widget
        type: string
  command:
    - sh
    - /action/main.sh

